version: '3'

services:
  postgres_source:
    image: postgres:13
    container_name: source_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customers_db
    ports:
      - "5432:5432"
    volumes:
      - ./data_sources/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_source:
    image: mysql:8
    container_name: source_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data_sources/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: source_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: source_postgres
